<?php

namespace AppBundle\Repository;

/**
 * CharacterHeadOverlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterHeadOverlayRepository extends \Doctrine\ORM\EntityRepository
{
}
