<?php

namespace AppBundle\Repository;

/**
 * CharacterFaceFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterFaceFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
