<?php

namespace AppBundle\Repository;

/**
 * JobVehiclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobVehiclesRepository extends \Doctrine\ORM\EntityRepository
{
}
